name: task_manager
description: Task Manager com camera, shake e GPS
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  connectivity_plus: ^5.0.2
  http: ^1.2.2

  camera: ^0.10.5+9
  sensors_plus: ^4.0.2
  vibration: ^3.1.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.3.1

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
